# Generated by Django 5.1.3 on 2024-11-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.CharField(max_length=255)),
                ('short_link', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
